### ISSUE TITLE
Spike: AutoDoc Architecture

### ISSUE THREAD

**Issue by PhilipLeddin** [sprinteins/oscd-plugins#101]
Spike: AutoDoc Architecture 

ACs:

- [x] we have a common understanding of the plugin architecture
- [x] clarification how and when to publish documentations

**Comment by michelguerin** [comment]
next steps are covered by the following issues:
#119 
#117 
#116

**Comment by michelguerin** [comment]
We are closing this issue because the scope have been covered.
