### ISSUE TITLE
Interview - Summary

### ISSUE THREAD

**Issue by PhilipLeddin** [sprinteins/oscd-plugins#123]
Interview - summary of following interviews:

Interviews:
- Interview 1 - AutoDoc 
- Interview 2 - AutoDoc 
- Interview 3 - AutoDoc 
- Interview 4 - AutoDoc 
- Interview 5 - AutoDoc 

- Interview 1 - TypeDesigner 
- Interview 2 - TypeDesigner 
- Interview 3 - TypeDesigner 
- Interview 4 - TypeDesigner
- Interview 5 - TypeDesigner

**Comment by LissiEitel** [comment]
First draft in youtrack: https://youtrack.sprinteins.com/articles/TBW-A-59/ADR-Interview-Summary 
After Feedback will be published to Zulip.

**Comment by LissiEitel** [comment]
Published to Zulip. Final Summary here: https://github.com/sprinteins/oscd-plugins/issues/170
