### ISSUE TITLE
Change the name of a Type directly on its creation

### ISSUE THREAD

**Issue by illia-solovei-s1** [sprinteins/oscd-plugins#138]
Change the name of a Type directly on its creation

As a User
I want to be able to adjust the name of a new type as soon as its being created
So that I don't have to go back to the drawer to change it every time

AC:
- [ ] Adding a new type to a column should be followed by adjusting the name of the new type
- [ ] If the user presses Enter without replacing the default placeholder, the name should be in the format of "[Type Name] [Id]"

![Image](https://github.com/user-attachments/assets/011ba0fd-cf4f-4884-9e99-e5ae43640b15)

**Comment by michelguerin** [comment]
Close this one as it has been handled differently.
