### ISSUE TITLE
Create and Organise Type-References with Drag and Drop

### ISSUE THREAD

**Issue by illia-solovei-s1** [sprinteins/oscd-plugins#166]
Story: Adding DND integration
As a User
I want to be able to drag and drop types from column to column
To make it easier for me to manipulate them.

AC:

- [ ] Enable drag and drop functionality
- [ ] Allow types to be moved from the original column to a neighbouring column on the left.

**Comment by PhilipLeddin** [comment]
Possible to drag:
LN-Types to all other columns
