### ISSUE TITLE
Documentation Plugin Download White Screen

### ISSUE THREAD

**Issue by trusz** [sprinteins/oscd-plugins#186]

**Comment by trusz** [comment]
I've found out the problem with the white screen, but the documentation still does not look correct.
PR Darft and branch: https://github.com/sprinteins/oscd-plugins/pull/185

**Comment by LissiEitel** [comment]
@michelguerin this is the only screenshot i have: 
![Bildschirmfoto 2024-10-09 um 11 21 22](https://github.com/user-attachments/assets/2f3eb92d-31fc-4c49-9bf4-af0ff42d0ab7)
