### ISSUE TITLE
Performance Analyse

### ISSUE THREAD

**Issue by PhilipLeddin** [sprinteins/oscd-plugins#40]
Analysieren der Performance im Communication Explorer bei größeren Dateien.

Beschreibung:
Optionen / Hinweise:
Analysephase
Performance-Bewertung und Benchmarking – das Tracking der Performance-
Optimierungen erlaubt es uns die umgesetzten Maßnahmen kurzfristig, mittelfristig
und langfristig zu prüfen, um entsprechend reagieren zu können. Dies kann per
manuellem Testplan mittels Performance Tests geprüft werden, um direkt bei
Auffälligkeiten reagieren zu können.
• Umfassende Analyse der aktuellen Performance-Probleme.
• Identifizierung von Engpässen und Verbesserungsbereichen.
• Dokumentation als Diagramm.

Code-Optimierung
• Refaktorisierung des Codes zur Steigerung der Effizienz.

Manuelle Last- und Stresstests
• Durchführung rigoroser Tests zur Sicherstellung der Softwareleistung unter Spitzenbelastungen.

Caching und Speicherverwaltung
• Implementierung von Caching-Strategien.
• Optimierung der Speichernutzung zur Verbesserung der Stabilität.

**Comment by clepski** [comment]
Das laden der Informationen aus der SCD Datei dauert teilweise sehr lang, hier ein Beispiel mit einer 12 MB großen SCD, die Methode `UCCommunicationInformation#IEDCommInfos` benötigt knapp 10 Sekunden und löst rund 100 Queries in die SCD aus.

### Lösungsideen

- Mehrere Queries sammeln und gemeinsam in der SCD suchen (ist es möglich einen Query pro IED zu erreichen?)
- Elemente (ControlBlock, ExtRef, etc) cachen, hier ist noch unklar ob die Elemente überhaupt mehrfach aus der SCD geladen werden

![Screenshot 2024-08-23 at 14 44 44](https://github.com/user-attachments/assets/033070f2-e4b0-474a-ba9f-d8e2fd4d4bf2)
