### ISSUE TITLE
Suche im Sidebar-Dropdown

### ISSUE THREAD

**Issue by PhilipLeddin** [sprinteins/oscd-plugins#41]
Als Anwender will ich im Sidebar-Dropdown des Communication Explorers die IEDs auch per Suche auswählen können, um keine Zeit mit dem scrollen durch die IEDs zu verschwenden.

ACs:
- Das Sidebar-Dropown oben rechts kann auch als Suche genutzt werden während die Dropdown Funktionalität bestehen bleibt
- Wenn man sucht werden automatisch passende IEDs angezeigt und die Liste reduziert sich basierend darauf
- Wenn man ein Suchergebnis auswählt wird passend dazu die IED in der Sidebar und auch im Diagramm ausgewählt
- Man kann per x Button die Suche zurücksetzen

![Bildschirmfoto 2024-08-22 um 10 47 07](https://github.com/user-attachments/assets/d4ad54f0-1532-4b2c-80da-c88dcc50fae0)

**Comment by michelguerin** [comment]
@interBN When changing the search without using the clear all button, if there is only one choice in the dropdown, it is selected by default, but the change is not taken into account (and selecting it doesn't have any effect)

https://github.com/user-attachments/assets/5dddc734-2d8a-424f-9c73-293ffcf377b8
