### ISSUE TITLE
Performance Optimierung

### ISSUE THREAD

**Issue by PhilipLeddin** [sprinteins/oscd-plugins#42]
Performance Optimierung basierend auf der Analyse in Ticket 40 (Performance Analyse)
https://github.com/sprinteins/oscd-plugins/issues/40

Lösungsideen
- Mehrere Queries sammeln und gemeinsam in der SCD suchen (ist es möglich einen Query pro IED zu erreichen?)
- Elemente (ControlBlock, ExtRef, etc) cachen, hier ist noch unklar ob die Elemente überhaupt mehrfach aus der SCD geladen werden

Hinweise:
- Lösungsvorschläge aus Kommentar in Ticket 40

**Comment by michelguerin** [comment]
Resolved #51
