### ISSUE TITLE
IED Details - Pt.1

### ISSUE THREAD

**Issue by PhilipLeddin** [sprinteins/oscd-plugins#5]
As a user, I want to be able to select IEDs to view details.

ACs:
- [x] it is possible to select "devices" to see details in sidebar (via click)

Basic details in the MVP:
- [ ] ~~IED Typ~~
- [ ] ~~Hersteller~~
- [x] IED name
- [x] IP adress
- [x] IP gateway
- [x] IP submit
- [x] cable name
- [x] connected IEDs
- [x] connected IED names

Further details in the next ticket:
- https://github.com/sprinteins/oscd-plugins/issues/6

UI: (siehe Sidebar Details in Communication Explorer)
IED Name (in Petrol Button)
   - IP Adress (in Textform)
   - IP Gateway (in Textform)
   - IP Submit (in Textform)
- Cable Name (Dropdown Bereich)
   - Connected IED (Text Headline)
   - IED Name (in White Box)

**Comment by PhilipLeddin** [comment]
<img width="1820" alt="MVP Details in Sidebar" src="https://github.com/sprinteins/oscd-plugins/assets/146182358/63307ab5-d895-42b0-9cc9-e59745f37308">

**Comment by trusz** [comment]
We won't add "IED Typ" and "Hersteller" in this ticket
